### ISSUE TITLE
Checkboxes, ripples noUISlider aint working

### ISSUE THREAD

**Issue by DanielMartinus** [romdim/yii2-bootstrap-material#1]
A couple of UI elements do not work as they do with the bootstrap of fezvrasta.

For example, buttons do not show a ripple effect, noUISlider does not appear and checkboxes are invisible.

**Comment by DanielMartinus** [comment]
Fixed by adding in body:
      `$(function() {
           $.material.init();
       });``

**Comment by romdim** [comment]
Yeap, you'll have to include this yourself as it is optional.. Sorry for taking to long to answer! Happy Easter!

**Comment by re1naldo** [comment]
Can you add this to the main documentation, please? It would be very helpful. Thanks!
