### ISSUE TITLE
css files not found

### ISSUE THREAD

**Issue by veyselsahin** [romdim/yii2-bootstrap-material#2]
Hi Romanos,
I am using your package but there is a new issue.
'css/material-fullpalette.min.css' file cannot found i guess its because bower bootstrap-material-design package's owner removed this file?

**Comment by romdim** [comment]
Hello @veyselsahin , I guess that's the issue too. I'll try to update it asap!

**Comment by romdim** [comment]
Hey @veyselsahin, are you using it currently in a project to double-check it's ok now? Thanks! And sorry for the delay..

**Comment by veyselsahin** [comment]
Hı @romdim i am using it in a project. Are you need old files ?

**Comment by romdim** [comment]
No, just checking to see if everything worked out!

**Comment by veyselsahin** [comment]
Hi i didnt update project i will say you after update. Thanks
