### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by klonwar** [romdim/yii2-bootstrap-material#8]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for romdim/yii2-bootstrap-material dev-master -> satisfiable by romdim/yii2-bootstrap-material[dev-master].
    - romdim/yii2-bootstrap-material dev-master requires bower-asset/bootstrap-material-design * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.`

**Comment by romdim** [comment]
Which composer version do you use?
It seems that it's composer-related as mentioned here as well (dated 2008 though, so I could be wrong, I need more info to be sure):
https://www.bountysource.com/issues/7020296-bower-packages-are-updated-constantly

**Comment by kennyballou** [comment]
Running the latest version of composer from https://getcomposer.org/installer, version 1.6.2, this issue still persists.

I also noticed that on packagelist, the aforementioned dependency doesn't link to anything.  Is this common on packagelist? Is that a red herring?

**Comment by romdim** [comment]
Hey Kenny!

Can you give me some more insight on what's wrong?
Steps to reproduce?
I've transitioned from php-yii2 to ruby-rails development for more than a year now and need to remember my stuff..

About the link, do you mean this one: https://packagist.org/packages/romdim/yii2-bootstrap-material#dev-master ?

**Comment by kennyballou** [comment]
I get the same error as the opening issue text, unable to satisfy the dependencies of `romdim/yii2-bootstrap-material`, unable to find `bower-asset/bootstrap-material-design`.

Here is a minimal example `compose.json` file that when run with `composer install` or `composer update` will show the error:

```json
{
    "name": "composer-bug-minimal",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "romdim/yii2-bootstrap-material": "*"
    }
}
```

I get the following error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - romdim/yii2-bootstrap-material dev-material-version-0-2-2 requires bower-asset/bootstrap-material-design 0.2.x -> no matching package found.
    - romdim/yii2-bootstrap-material dev-master requires bower-asset/bootstrap-material-design * -> no matching package found.
    - romdim/yii2-bootstrap-material 1.0 requires bower-asset/bootstrap-material-design * -> no matching package found.
    - romdim/yii2-bootstrap-material 0.1.3 requires bower-asset/bootstrap-material-design * -> no matching package found.
    - romdim/yii2-bootstrap-material 0.1.2 requires bower-asset/bootstrap-material-design * -> no matching package found.
    - romdim/yii2-bootstrap-material 0.1.1 requires bower-asset/bootstrap-material-design * -> no matching package found.
    - romdim/yii2-bootstrap-material 0.1 requires bower-asset/bootstrap-material-design * -> no matching package found.
    - Installation request for romdim/yii2-bootstrap-material * -> satisfiable by romdim/yii2-bootstrap-material[0.1, 0.1.1, 0.1.2, 0.1.3, 1.0, dev-master, dev-material-version-0-2-2].
```

For the time being, I've removed the dependency from my project, but as someone new to an internal legacy project, I'm not sure this is the long term solution.

With regards to link: I mean the link to `bower-asset/bootstrap-material-design` dependency when viewing the [package](https://packagist.org/packages/romdim/yii2-bootstrap-material).


Any help much appreciated.

**Comment by kennyballou** [comment]
I may have discovered a reason for this breaking in my instance.  I'm not sure this resolves the issue for @klonwar...

In my case, adding `npm` and `bower` to the path was what fixed the issue.  I had a number of other dependencies that were breaking and adding these corrected the issue.

To be more precise:

In an alpine docker container, I had added `nodejs-npm` (and `yarn` for "reasons") via `apk add nodejs-npm yarn` then `yarn global add bower`. After this, I was able to successfully run `composer update`.

**Comment by romdim** [comment]
And that's definitely the case why it broke. You need bower in order to install the dependencies. I'll guess I'll have to declare this in the readme. Thanks for the clarification! And cheers for using docker! (and this package of course..)

**Comment by romdim** [comment]
Btw you could use the official: https://github.com/yidas/yii2-bower-asset or https://github.com/fxpio/composer-asset-plugin to solve everything via yii2 and composer instead of having to install bower..
I haven't tested them but assume they work just fine in this case!
